# Change this file when releasing a new version.
# You'll also need to add a new changelog entry in:
#   debian/changelog
#   dist/clementine.spec.in

# Version numbers.  For m.n rc, use m.(n-1).99
set(CLEMENTINE_VERSION_MAJOR 0)
set(CLEMENTINE_VERSION_MINOR 3)

set(BUILDBOT_REVISION $ENV{BUILDBOT_REVISION})
if(BUILDBOT_REVISION)
  set(CLEMENTINE_VERSION_PATCH 90)
  set(CLEMENTINE_VERSION_STRING "0.3 - buildbot r${BUILDBOT_REVISION}") # Displayed in GUIs
  set(CLEMENTINE_VERSION_SHORT_STRING "0.3r${BUILDBOT_REVISION}")       # Used in filenames
else(BUILDBOT_REVISION)
  set(CLEMENTINE_VERSION_PATCH 0)
  set(CLEMENTINE_VERSION_STRING "0.3")
  set(CLEMENTINE_VERSION_SHORT_STRING "0.3")
endif(BUILDBOT_REVISION)


if (CLEMENTINE_VERSION_PATCH)
  set(CLEMENTINE_VERSION ${CLEMENTINE_VERSION_MAJOR}.${CLEMENTINE_VERSION_MINOR}.${CLEMENTINE_VERSION_PATCH})
else (CLEMENTINE_VERSION_PATCH)
  set(CLEMENTINE_VERSION ${CLEMENTINE_VERSION_MAJOR}.${CLEMENTINE_VERSION_MINOR})
endif (CLEMENTINE_VERSION_PATCH)
